apiVersion: v2
name: devops-demo
version: 0.1.0
appVersion: "0.1.0"
description: Umbrella chart for app (bjw-s app-template) + Redis + External Secrets
kubeVersion: ">=1.25.0-0"
type: application

dependencies:
  - name: app-template
    alias: app
    repository: https://bjw-s-labs.github.io/helm-charts
    version: ">=3.0.0"
    condition: app.enabled
  - name: redis
    alias: redis
    repository: https://charts.bitnami.com/bitnami
    version: ">=19.0.0"
    condition: redis.enabled
  - name: kube-prometheus-stack
    alias: monitoringstack
    repository: https://prometheus-community.github.io/helm-charts
    version: ">=77.14.0"
    condition: monitoringstack.enabled
  - name: loki-stack
    alias: loggingstack
    repository: https://grafana.github.io/helm-charts
    version: ">=2.10.0"
    condition: loggingstack.enabled
  - name: ingress-nginx
    alias: ingressnginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: ">=4.10.0"
    condition: ingressNginx.enabled
